apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-deplo
  labels:
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: backend
  template:
    metadata:
      labels:
         tier: backend
    spec:
      containers:
      - name: food
        image: yellaiahdocker/backend
        ports:
        - containerPort: 3002
---


apiVersion: v1
kind: Service
metadata:
  name: food-servi
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3002
  selector: 
      tier: backend
