apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: backend
  template:
    metadata:
      labels:
         tier: backend
    spec:
      containers:
      - name: back
        image: yellaiahdocker/backend
        ports:
        - containerPort: 3002
