apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-deploy
  labels:
    tier: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: backend
  template:
    metadata:
      labels:
         tier: backend
    spec:
      containers:
      - name: food
        image: yellaiahdocker/food
        ports:
        - containerPort: 80
---


apiVersion: v1
kind: Service
metadata:
  name: food-servic
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector: 
      tier: backend
